# Generated by Django 3.2.10 on 2022-02-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='cif_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='id_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
