# Generated by Django 3.2.10 on 2022-02-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0002_auto_20220205_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionsModeEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trans_mode', models.CharField(max_length=500)),
            ],
        ),
    ]
