# Generated by Django 3.2.10 on 2022-02-09 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0003_transactionsmodeentity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='incorporation_number',
            new_name='organization_id',
        ),
    ]
