# Generated by Django 3.2.10 on 2022-02-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0004_rename_incorporation_number_organization_organization_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=30)),
                ('customer_type', models.CharField(max_length=30)),
                ('screen_date', models.CharField(max_length=20)),
            ],
        ),
    ]
