# Generated by Django 3.2.10 on 2022-02-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0005_screenstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenstatus',
            name='screen_date',
            field=models.CharField(max_length=40),
        ),
    ]
