# Generated by Django 3.2.10 on 2022-02-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0006_alter_screenstatus_screen_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='screening_status',
            new_name='screening_performed',
        ),
        migrations.AddField(
            model_name='organization',
            name='screening_performed',
            field=models.CharField(blank=True, default='No', max_length=10, null=True),
        ),
    ]
