# Generated by Django 3.2.10 on 2022-02-10 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0007_auto_20220210_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='screening_performed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='screening_performed',
            field=models.BooleanField(default=False),
        ),
    ]
