# Generated by Django 3.2.10 on 2022-02-10 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0008_auto_20220210_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenstatus',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='screenstatus',
            name='individual',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='identification.individual'),
        ),
        migrations.CreateModel(
            name='EntityScreenStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_type', models.CharField(max_length=30)),
                ('screen_date', models.CharField(max_length=40)),
                ('organization', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='identification.organization')),
            ],
        ),
    ]
