# Generated by Django 3.2.10 on 2022-02-10 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0009_auto_20220210_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='partner_id',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='partner_name',
        ),
    ]
