# Generated by Django 3.2.10 on 2022-02-10 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0010_auto_20220210_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='pep_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='identification.pep'),
        ),
    ]
