# Generated by Django 3.2.10 on 2022-02-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0011_alter_organization_pep_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTypeIndividual',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_type', models.CharField(max_length=30)),
            ],
        ),
    ]
