# Generated by Django 3.2.10 on 2022-02-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0012_accounttypeindividual'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
