# Generated by Django 3.2.10 on 2022-02-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redflags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FATFOwnedCompany',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('searched_type', models.CharField(blank=True, max_length=40, null=True)),
                ('risk_weight', models.IntegerField()),
                ('risk_category', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
        ),
    ]
