# Generated by Django 3.2.10 on 2022-02-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redflags', '0002_fatfownedcompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatfownedcompany',
            name='searched_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
