# Generated by Django 3.2.10 on 2022-02-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redflags', '0003_alter_fatfownedcompany_searched_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='demoTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_type', models.CharField(max_length=500)),
                ('risk_category', models.CharField(blank=True, max_length=20, null=True)),
                ('risk_weight', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
