# Generated by Django 3.2.10 on 2022-02-11 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redflags', '0004_demotable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negativenews',
            name='news_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
