# Generated by Django 3.2.10 on 2022-02-10 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0009_auto_20220210_1535'),
        ('riskrating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDDApprovalEmailRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('approval_email_sent', models.BooleanField(default=False)),
                ('approval_email_sent_time', models.CharField(default='', max_length=40, null=True)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identification.individual')),
            ],
        ),
    ]
