# Generated by Django 3.2.10 on 2022-02-14 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screeing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alertdatatemp',
            new_name='ScreenAlert',
        ),
        migrations.RenameModel(
            old_name='OrganizationAlerts',
            new_name='ScreenEntityAlerts',
        ),
        migrations.RenameModel(
            old_name='OrganizationSearchName',
            new_name='ScreenEntityDiscount',
        ),
        migrations.RenameModel(
            old_name='searchNameTemp',
            new_name='ScrenDiscount',
        ),
        migrations.DeleteModel(
            name='Screeingcustomer',
        ),
    ]
