# Generated by Django 3.2.10 on 2022-02-10 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entityalerts',
            old_name='org_registeration',
            new_name='org_id',
        ),
    ]
