# Generated by Django 3.2.10 on 2022-02-10 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0009_auto_20220210_1535'),
        ('discounting', '0002_rename_org_registeration_entityalerts_org_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='central_bank_email_record',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='l1_cases',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='self_analysis_cases',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='central_bank_email_record',
            name='alert_id',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='central_bank_email_record',
            name='individual',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='l1_cases',
            name='individual',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='identification.individual'),
        ),
        migrations.AddField(
            model_name='self_analysis_cases',
            name='individual',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='identification.individual'),
        ),
        migrations.AlterField(
            model_name='central_bank_email_record',
            name='customer_type',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='mlro_cases',
            name='customer_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='identification.individual'),
        ),
    ]
