# Generated by Django 3.2.10 on 2022-02-17 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0013_organization_country'),
        ('discounting', '0003_auto_20220210_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='L2_Cases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_id', models.CharField(max_length=25)),
                ('case_status', models.CharField(blank=True, default='', max_length=25, null=True)),
                ('individual', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='identification.individual')),
            ],
        ),
    ]
