# Generated by Django 3.2.10 on 2022-02-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounting', '0004_l2_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='individuldiscount',
            name='sent_to_L2',
            field=models.BooleanField(default=False),
        ),
    ]
