# Generated by Django 3.2.10 on 2022-02-05 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='STRData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspect_type', models.CharField(default='', max_length=300, null=True)),
                ('action_taken', models.CharField(default='', max_length=300, null=True)),
                ('bank_relationship', models.CharField(default='', max_length=300, null=True)),
                ('business_relationship', models.CharField(default='', max_length=300, null=True)),
                ('relationship_to_person', models.CharField(default='', max_length=300, null=True)),
                ('termination_date', models.CharField(default='', max_length=300, null=True)),
                ('transaction_capacity', models.CharField(default='', max_length=300, null=True)),
                ('funds_freeze', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('transaction_reject', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('account_reject', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identification.individual')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_report', models.CharField(default='', max_length=50, null=True)),
                ('monitoring_frequency', models.CharField(default='', max_length=50, null=True)),
                ('monitoring_timeline', models.CharField(default='', max_length=50, null=True)),
                ('individual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identification.individual')),
            ],
        ),
    ]
