USE compliance
-----------------------UNSC_INDIVIDUAL---------------------------
SELECT COUNT(*)
FROM UNSC_INDIVIDUAL

SELECT *
FROM UNSC_INDIVIDUAL
WHERE DATE_INSERTED = '18-05-2021 15:58'
WHERE DATAID = 2975510

DELETE FROM UNSC_INDIVIDUAL
TRUNCATE TABLE UNSC_INDIVIDUAL
DROP TABLE UNSC_INDIVIDUAL

-----------------------UNSC_INDIVIDUAL_ALIAS---------------------------
SELECT COUNT(*)
FROM UNSC_INDIVIDUAL_ALIAS

SELECT *
FROM UNSC_INDIVIDUAL_ALIAS
WHERE DATAID = 2975510

SELECT *
FROM UNSC_INDIVIDUAL_ALIAS AS a 
INNER JOIN UNSC_INDIVIDUAL AS b
ON a.DataID = b.DATAID
WHERE b.Dataid = 6908434


DELETE FROM UNSC_INDIVIDUAL_ALIAS
TRUNCATE TABLE UNSC_INDIVIDUAL_ALIAS
DROP TABLE UNSC_INDIVIDUAL_ALIAS

-----------------------UNSC_INDIVIDUAL_ADDRESS---------------------------
SELECT COUNT(*)
FROM UNSC_INDIVIDUAL_ADDRESS

SELECT *
FROM UNSC_INDIVIDUAL_ADDRESS
WHERE DATAID = 2975510

DELETE FROM UNSC_INDIVIDUAL_ADDRESS
TRUNCATE TABLE UNSC_INDIVIDUAL_ADDRESS
DROP TABLE UNSC_INDIVIDUAL_ADDRESS

-- ---------------------UNSC_INDIVIDUAL_DATE_OF_BIRTH---------------------------
SELECT COUNT(*)
FROM UNSC_INDIVIDUAL_DATE_OF_BIRTH

SELECT *
FROM UNSC_INDIVIDUAL_DATE_OF_BIRTH
WHERE DATAID = 2975510

DELETE FROM UNSC_INDIVIDUAL_DATE_OF_BIRTH
TRUNCATE TABLE UNSC_INDIVIDUAL_DATE_OF_BIRTH
DROP TABLE UNSC_INDIVIDUAL_DATE_OF_BIRTH

-- ---------------------UNSC_INDIVIDUAL_PLACE_OF_BIRTH---------------------------
SELECT COUNT(*)
FROM UNSC_INDIVIDUAL_PLACE_OF_BIRTH

SELECT *
FROM UNSC_INDIVIDUAL_PLACE_OF_BIRTH
WHERE DATAID  = '2833107'
WHERE NOTE IS NOT NULL

DELETE FROM UNSC_INDIVIDUAL_PLACE_OF_BIRTH
TRUNCATE TABLE UNSC_INDIVIDUAL_PLACE_OF_BIRTH
DROP TABLE UNSC_INDIVIDUAL_PLACE_OF_BIRTH

-- ---------------------UNSC_INDIVIDUAL_DOCUMENT---------------------------
SELECT COUNT(*)
FROM UNSC_INDIVIDUAL_DOCUMENT

SELECT *
FROM UNSC_INDIVIDUAL_DOCUMENT
WHERE DATAID = 2975510
WHERE NOTE IS NOT NULL

DELETE FROM UNSC_INDIVIDUAL_DOCUMENT
TRUNCATE TABLE UNSC_INDIVIDUAL_DOCUMENT
DROP TABLE UNSC_INDIVIDUAL_DOCUMENT

-- ---------------------INVIDUALS INNER JOIN---------------------------
SELECT DISTINCT *
FROM UNSC_INDIVIDUAL AS A
	LEFT JOIN UNSC_INDIVIDUAL_ALIAS AS B 
		ON A.DATAID = B.DATAID
	LEFT JOIN UNSC_INDIVIDUAL_ADDRESS AS C
		ON A.DATAID = C.DATAID
	LEFT JOIN UNSC_INDIVIDUAL_DATE_OF_BIRTH AS D
		ON A.DATAID = D.DATAID
	LEFT JOIN UNSC_INDIVIDUAL_PLACE_OF_BIRTH AS E
		ON A.DATAID = E.DATAID
	LEFT JOIN UNSC_INDIVIDUAL_DOCUMENT AS F
		ON A.DATAID = F.DATAID
WHERE A.DATE_INSERTED = (SELECT MAX(DATE_INSERTED)
			FROM UNSC_INDIVIDUAL)
AND A.DATAID  = '6908555'
-- --------------------UNSC_ENTITY---------------------------
SELECT COUNT(*)
FROM UNSC_ENTITY

SELECT *
FROM UNSC_ENTITY
WHERE DATE_INSERTED = '18-05-2021 16:30'

DELETE FROM UNSC_ENTITY
TRUNCATE TABLE UNSC_ENTITY
DROP TABLE UNSC_ENTITY
-- ---------------------UNSC_ENTITY_ALIAS---------------------------
SELECT COUNT(*)
FROM UNSC_ENTITY_ALIAS

SELECT *
FROM UNSC_ENTITY_ALIAS

DELETE FROM UNSC_ENTITY_ALIAS
TRUNCATE TABLE UNSC_ENTITY_ALIAS
DROP TABLE UNSC_ENTITY_ALIAS
-- ---------------------UNSC_ENTITY_ADDRESS---------------------------
SELECT COUNT(*)
FROM UNSC_ENTITY_ADDRESS

SELECT *
FROM UNSC_ENTITY_ADDRESS

DELETE FROM UNSC_ENTITY_ADDRESS
TRUNCATE TABLE UNSC_ENTITY_ADDRESS
DROP TABLE UNSC_ENTITY_ADDRESS
-- ---------------------UNSC TRUNCATE QUERY---------------------------
TRUNCATE TABLE UNSC_INDIVIDUAL;
TRUNCATE TABLE UNSC_INDIVIDUAL_ADDRESS;
TRUNCATE TABLE UNSC_INDIVIDUAL_DATE_OF_BIRTH;
TRUNCATE TABLE UNSC_INDIVIDUAL_PLACE_OF_BIRTH;
TRUNCATE TABLE UNSC_INDIVIDUAL_DOCUMENT;
TRUNCATE TABLE UNSC_ENTITY;
TRUNCATE TABLE UNSC_ENTITY_ALIAS;
TRUNCATE TABLE UNSC_ENTITY_ADDRESS;
-- ---------------------UNSC ENTITY INNER JOIN---------------------------
SELECT *
FROM UNSC_ENTITY AS A
	LEFT JOIN UNSC_ENTITY_ALIAS AS B 
		ON A.DATAID = B.DATAID
	LEFT JOIN UNSC_ENTITY_ADDRESS AS C
		ON A.DATAID = C.DATAID	
WHERE A.DATE_INSERTED = (SELECT MAX(DATE_INSERTED)
			FROM UNSC_ENTITY)
-- ---------------------NACTA_PROSCRIBED_PERSONS--------------------------
SELECT COUNT(*)
FROM NACTA_PROSCRIBED_PERSONS

SELECT *
FROM NACTA_PROSCRIBED_PERSONS
WHERE `NAME` LIKE '%Abdul Hameed%'
DISCREPANT_CHECK LIKE '1|0|1'

DELETE FROM NACTA_PROSCRIBED_PERSONS
TRUNCATE TABLE NACTA_PROSCRIBED_PERSONS
DROP TABLE NACTA_PROSCRIBED_PERSONS
-- ---------------------OFAC--------------------------
SELECT COUNT(*)
FROM OFAC

SELECT *
FROM OFAC
WHERE LAST_NAME = 'Abu Nidal Organisation'


DELETE FROM OFAC
TRUNCATE TABLE OFAC
DROP TABLE OFAC
-- ---------------------OFAC_ALIAS--------------------------
SELECT COUNT(*)
FROM OFAC_ALIAS

SELECT *
FROM OFAC_ALIAS
WHERE FIRST_NAME = 'Abu Nidal Organisation'

DELETE FROM OFAC_ALIAS
TRUNCATE TABLE OFAC_ALIAS
DROP TABLE OFAC_ALIAS
-- ---------------------OFAC_DATE_OF_BIRTH--------------------------
SELECT COUNT(*)
FROM OFAC_DATE_OF_BIRTH

SELECT *
FROM OFAC_DATE_OF_BIRTH

DELETE FROM OFAC_DATE_OF_BIRTH
TRUNCATE TABLE OFAC_DATE_OF_BIRTH
DROP TABLE OFAC_DATE_OF_BIRTH
-- ---------------------OFAC_PLACE_OF_BIRTH--------------------------
SELECT COUNT(*)
FROM OFAC_PLACE_OF_BIRTH

SELECT *
FROM OFAC_PLACE_OF_BIRTH

DELETE FROM OFAC_PLACE_OF_BIRTH
TRUNCATE TABLE OFAC_PLACE_OF_BIRTH
DROP TABLE OFAC_PLACE_OF_BIRTH
-- ---------------------OFAC_ADDRESS--------------------------
SELECT COUNT(*)
FROM OFAC_ADDRESS

SELECT *
FROM OFAC_ADDRESS

DELETE FROM OFAC_ADDRESS
TRUNCATE TABLE OFAC_ADDRESS
DROP TABLE OFAC_ADDRESS
-- ---------------------OFAC_CITIZENSHIP--------------------------
SELECT COUNT(*)
FROM OFAC_CITIZENSHIP

SELECT *
FROM OFAC_CITIZENSHIP

DELETE FROM OFAC_CITIZENSHIP
TRUNCATE TABLE OFAC_CITIZENSHIP
DROP TABLE OFAC_CITIZENSHIP
-- ---------------------OFAC_ID--------------------------
SELECT COUNT(*)
FROM OFAC_ID

SELECT *
FROM OFAC_ID AS A INNER JOIN OFAC AS B
ON A.DATAID =B.DATAID

DELETE FROM OFAC_ID
TRUNCATE TABLE OFAC_ID
DROP TABLE OFAC_ID
-- ---------------------OFAC INNER JOIN---------------------------
SELECT *
FROM OFAC AS A
	LEFT JOIN OFAC_ALIAS AS B 
		ON A.DATAID = B.DATAID
	LEFT JOIN OFAC_DATE_OF_BIRTH AS C
		ON A.DATAID = C.DATAID
	LEFT JOIN OFAC_PLACE_OF_BIRTH AS D
		ON A.DATAID = D.DATAID
	LEFT JOIN OFAC_ADDRESS AS E
		ON A.DATAID = E.DATAID
	LEFT JOIN OFAC_CITIZENSHIP AS F
		ON A.DATAID = F.DATAID
	LEFT JOIN OFAC_ID AS G
		ON A.DATAID = G.DATAID
WHERE A.DATE_INSERTED = (SELECT MAX(DATE_INSERTED)
			FROM OFAC)
			
			
TRUNCATE TABLE OFAC_ID;
TRUNCATE TABLE OFAC_CITIZENSHIP;
TRUNCATE TABLE OFAC_ADDRESS;
TRUNCATE TABLE OFAC_PLACE_OF_BIRTH;
TRUNCATE TABLE OFAC_DATE_OF_BIRTH;
TRUNCATE TABLE OFAC_ALIAS;
TRUNCATE TABLE OFAC;
-- ---------------------OFSI--------------------------
SELECT COUNT(*)
FROM OFSI

SELECT *
FROM OFSI
WHERE FullName = 'Abu Nidal Organisation'

DELETE FROM OFSI
TRUNCATE TABLE OFSI
DROP TABLE OFSI
-- ---------------------EUFS--------------------------
SELECT COUNT(*)
FROM EUFS

SELECT BirthDate_Region, 
BirthDate_Place, 
BirthDate_City,
Address_City ,
Address_Street ,
Address_Region ,
Address_Place ,
Address_AsAtListingTime ,
Address_ContactInfo ,
Address_CountryIso2Code ,
Address_CountryDescription ,
Identification_Region 
Citizenship_Region,
Citizenship_CountryIso2Code
FROM EUFS
WHERE Address_Place != 'NULL'
WHERE Identification_Number IS NOT NULL AND Identification_Number LIKE '%3520025509842-7%'

SELECT  Entity_SubjectType_ClassificationCode
FROM EUFS

DELETE FROM EUFS
TRUNCATE TABLE EUFS
DROP TABLE EUFS
-- ---------------------NACTA_PROSCRIBED_ORGANIZATIONS--------------------------
SELECT COUNT(*)
FROM NACTA_PROSCRIBED_ORGANIZATIONS

SELECT *
FROM NACTA_PROSCRIBED_ORGANIZATIONS

DELETE FROM NACTA_PROSCRIBED_ORGANIZATIONS
TRUNCATE TABLE NACTA_PROSCRIBED_ORGANIZATIONS
DROP TABLE NACTA_PROSCRIBED_ORGANIZATIONS
-- ---------------------NACTA_PROSCRIBED_ORGANIZATIONS--------------------------
SELECT COUNT(*)
FROM NACTA_PROSCRIBED_PERSONS_DENOTIFIED

SELECT *
FROM NACTA_PROSCRIBED_PERSONS_DENOTIFIED

DELETE FROM NACTA_PROSCRIBED_PERSONS_DENOTIFIED
TRUNCATE TABLE NACTA_PROSCRIBED_PERSONS_DENOTIFIED
DROP TABLE NACTA_PROSCRIBED_PERSONS_DENOTIFIED
-- ---------------------OFAC_SDN--------------------------
SELECT COUNT(*)
FROM OFAC_SDN

SELECT *
FROM OFAC_SDN
WHERE dataid LIKE '%3520025509842%'

DELETE FROM OFAC_SDN
TRUNCATE TABLE OFAC_SDN
DROP TABLE OFAC_SDN
-- ---------------------OFAC_SDN_SDN_ALIAS--------------------------
SELECT COUNT(*)
FROM OFAC_SDN_ALIAS

SELECT *
FROM OFAC_SDN_ALIAS

DELETE FROM OFAC_SDN_ALIAS
TRUNCATE TABLE OFAC_SDN_ALIAS
DROP TABLE OFAC_SDN_ALIAS
-- ---------------------OFAC_SDN_DATE_OF_BIRTH--------------------------
SELECT COUNT(*)
FROM OFAC_SDN_SDN_ATE_OF_BIRTH

SELECT *
FROM OFAC_SDN_DATE_OF_BIRTH

DELETE FROM OFAC_SDN_DATE_OF_BIRTH
TRUNCATE TABLE OFAC_SDN_DATE_OF_BIRTH
DROP TABLE OFAC_SDN_DATE_OF_BIRTH
-- ---------------------OFAC_SDN_PLACE_OF_BIRTH--------------------------
SELECT COUNT(*)
FROM OFAC_SDN_PLACE_OF_BIRTH

SELECT *
FROM OFAC_SDN_PLACE_OF_BIRTH

DELETE FROM OFAC_SDN_PLACE_OF_BIRTH
TRUNCATE TABLE OFAC_SDN_PLACE_OF_BIRTH
DROP TABLE OFAC_SDN_PLACE_OF_BIRTH
-- ---------------------OFAC_SDN_ADDRESS--------------------------
SELECT COUNT(*)
FROM OFAC_SDN_ADDRESS

SELECT *
FROM OFAC_SDN_ADDRESS AS A
INNER JOIN OFAC_SDN_CITIZENSHIP AS B
ON A.DATAID = B.DATAID
INNER JOIN OFAC_SDN_NATIONALITY AS C
ON A.DATAID = C.DATAID
ORDER BY 1

DELETE FROM OFAC_SDN_ADDRESS
TRUNCATE TABLE OFAC_SDN_ADDRESS
DROP TABLE OFAC_SDN_ADDRESS
-- ---------------------OFAC_SDN_NATIONALITY--------------------------
SELECT COUNT(*)
FROM OFAC_SDN_NATIONALITY

SELECT *
FROM OFAC_SDN_NATIONALITY

DELETE FROM OFAC_SDN_NATIONALITY
TRUNCATE TABLE OFAC_SDN_NATIONALITY
DROP TABLE OFAC_SDN_NATIONALITY
-- ---------------------OFAC_SDN_CITIZENSHIP--------------------------
SELECT COUNT(*)
FROM OFAC_SDN_CITIZENSHIP

SELECT *
FROM OFAC_SDN_CITIZENSHIP

DELETE FROM OFAC_SDN_CITIZENSHIP
TRUNCATE TABLE OFAC_SDN_CITIZENSHIP
DROP TABLE OFAC_SDN_CITIZENSHIP
-- ---------------------OFAC_SDN_ID--------------------------
SELECT COUNT(*)
FROM OFAC_SDN_ID

SELECT *
FROM OFAC_SDN_ID
WHERE ID_NUMBER LIKE '%3520025509842%'
 AS A INNER JOIN OFAC_SDN AS B
ON A.DATAID =B.DATAID

/*DELETE FROM OFAC_SDN_ID
TRUNCATE TABLE OFAC_SDN_ID
DROP TABLE OFAC_SDN_ID
DROP TABLE OFAC_SDN_CITIZENSHIP*/
-- ---------------------OFAC_SDN_VESSEL_INFO--------------------------
SELECT COUNT(*)
FROM OFAC_SDN_VESSEL_INFO

SELECT *
FROM OFAC_SDN_VESSEL_INFO 

DELETE FROM OFAC_SDN_VESSEL_INFO
TRUNCATE TABLE OFAC_SDN_VESSEL_INFO
DROP TABLE OFAC_SDN_VESSEL_INFO

TRUNCATE TABLE OFAC_SDN;
TRUNCATE TABLE OFAC_SDN_VESSEL_INFO;
TRUNCATE TABLE OFAC_SDN_ID;
TRUNCATE TABLE OFAC_SDN_CITIZENSHIP;
TRUNCATE TABLE OFAC_SDN_NATIONALITY;
TRUNCATE TABLE OFAC_SDN_ADDRESS;
TRUNCATE TABLE OFAC_SDN_PLACE_OF_BIRTH;
TRUNCATE TABLE OFAC_SDN_DATE_OF_BIRTH;
TRUNCATE TABLE OFAC_SDN_ALIAS;

-- ---------------------consolidate_list---------------------------------
SELECT * -- STR_TO_DATE(DOB, '%Y-%m-%d') as a,DOB,STR_TO_DATE(DOB, '%d %b %Y')  as b,STR_TO_DATE(DOB, '%d/%m/%Y') AS C
FROM consolidate_list

SELECT dob,
CASE     
    WHEN STR_TO_DATE(DOB, '%Y-%m-%d') != '(NULL)' THEN STR_TO_DATE(DOB, '%Y-%m-%d')
    WHEN STR_TO_DATE(DOB, '%d %b %Y') != '(NULL)' THEN STR_TO_DATE(DOB, '%d %b %Y')     
    WHEN STR_TO_DATE(DOB, '%d/%m/%Y') != '(NULL)' THEN STR_TO_DATE(DOB, '%d/%m/%Y') 
    ELSE "0000-00-00"    
END AS DOB1
FROM consolidate_list

SELECT
CAST(CASE 
    WHEN STR_TO_DATE(DOB, '%Y-%m-%d') != '(NULL)' THEN STR_TO_DATE(DOB, '%Y-%m-%d')
    WHEN STR_TO_DATE(DOB, '%d %b %Y') != '(NULL)' THEN STR_TO_DATE(DOB, '%d %M %Y')
    WHEN STR_TO_DATE(DOB, '%d/%m/%Y') != '(NULL)' THEN STR_TO_DATE(DOB, '%d/%m/%Y') 
    ELSE "0000-00-00"    
END )  VARCHAR
FROM consolidate_list



SELECT STR_TO_DATE('1960-01-01-05:00', '%Y-%m-%d') AS A 

ORDER BY 1	
WHERE `NAME` LIKE '%HAFIZ MUHAMMAD SAEED%'
AND `List` = 'UNSC'
'%HAFIZ MUHAMMAD SAEED%'


ORDER BY 1
WHERE ID_NUMBER LIKE '%3520025509842-7%'
AND `LIST` = 'OFAC_SDN'


SELECT DATAID, GROUP_CONCAT(ALIAS)
FROM consolidate_list
DATE_INSERTED = (SELECT MAX(DATE_INSERTED)
			FROM consolidate_list)
AND ALIAS IS NOT NULL OR ALIAS != '' OR ALIAS != ' '
AND DATAID IS NOT NULL OR DATAID != 'NIL' OR DATAID != 'NULL'


SELECT *
FROM consolidate_list
WHERE `list` = 'NACTA_PROSCRIBED_PERSONS'
WHERE ID_NUMBER LIKE '%1730143807325%'

SELECT DATAID, `LIST`
FROM consolidate_list
GROUP BY DATAID,`LIST`
HAVING DATAID = 6908434

SELECT *
FROM consolidate_list
WHERE DATAID = 0000000000000

TRUNCATE TABLE consolidate_list;
	
CALL CONSOLIDATED_LIST_SEARCH_INTO

-- ---------------------Geographic Location--------------------------
SELECT COUNT(*)
FROM geographic_location

SELECT *
FROM geographic_location

DELETE FROM geographic_location
TRUNCATE TABLE geographic_location
DROP TABLE geographic_location

-- ---------------------Customer TYPE--------------------------
SELECT COUNT(*)
FROM customer_type

SELECT *
FROM customer_type

DELETE FROM customer_type
TRUNCATE TABLE customer_type
DROP TABLE customer_type

-- ---------------------Product TYPE--------------------------
SELECT COUNT(*)
FROM Product_TYPE

SELECT *
FROM Product_TYPE

DELETE FROM Product_TYPE
TRUNCATE TABLE Product_TYPE
DROP TABLE Product_TYPE

-- ---------------------Country Nationality-------------------------
SELECT COUNT(*)
FROM Country_Nationality

SELECT *
FROM Country_Nationality

DELETE FROM Country_Nationality
TRUNCATE TABLE Country_Nationality
DROP TABLE Country_Nationality

-- ---------------------Delivery Channel-------------------------
SELECT COUNT(*)
FROM delivery_channel

SELECT *
FROM delivery_channel

DELETE FROM delivery_channel
TRUNCATE TABLE delivery_channel
DROP TABLE delivery_channel

-- ---------------------Api_Call_Record---------------------
SELECT COUNT(*)
FROM Api_Call_Record

SELECT *
FROM Api_Call_Record

DELETE FROM Api_Call_Record
TRUNCATE TABLE Api_Call_Record
DROP TABLE Api_Call_Record