DELIMITER //
CREATE PROCEDURE CONSOLIDATED_SEARCH_LIST()
BEGIN
SELECT A.*
FROM (

	SELECT DISTINCT (A.DATAID), CONCAT_WS(' ',A.FIRST_NAME, A.SECOND_NAME, A.THIRD_NAME, A.FOURTH_NAME, C.ALIAS_NAME) AS 'Name', CONCAT_WS(' ',B.CITY, B.STATE_PROVINCE, B.COUNTRY) AS 'Address', 'UNSC' AS 'List', 'INDIVIDUAL' AS 'Type'
	FROM UNSC_INDIVIDUAL AS A
	LEFT JOIN UNSC_INDIVIDUAL_ADDRESS AS B
	ON A.DATAID = B.DATAID
	LEFT JOIN UNSC_INDIVIDUAL_ALIAS AS C
	ON A.DATAID = C.DATAID
	WHERE A.DATE_INSERTED = (SELECT MAX(DATE_INSERTED)
				FROM UNSC_INDIVIDUAL)
			
	UNION

	SELECT DISTINCT (A.DATAID), CONCAT_WS(' ',A.FIRST_NAME, C.ALIAS_NAME) AS 'Name', CONCAT_WS(' ',B.CITY, B.STATE_PROVINCE, B.COUNTRY) AS 'Address', 'UNSC' AS 'List', 'ENTITY' AS 'Type'
	FROM UNSC_ENTITY AS A
	LEFT JOIN UNSC_ENTITY_ADDRESS AS B
	ON A.DATAID = B.DATAID
	LEFT JOIN UNSC_ENTITY_ALIAS AS C
	ON A.DATAID = C.DATAID
	WHERE A.DATE_INSERTED = (SELECT MAX(DATE_INSERTED)
				FROM UNSC_ENTITY)		
			
	UNION

	SELECT CNIC AS 'DATAID', `Name`, CONCAT_WS(' ',PROVINCE, DISTRICT) AS 'Address' , 'NACTA_PROSCRIBED_PERSONS' AS 'List', 'INDIVIDUAL' AS 'Type'
	FROM NACTA_PROSCRIBED_PERSONS
	WHERE `Name` IS NOT NULL 
	AND DATE_INSERTED =(SELECT MAX(DATE_INSERTED)
				FROM NACTA_PROSCRIBED_PERSONS)

	UNION

	SELECT DISTINCT (A.DATAID), CONCAT_WS(' ',A.FIRST_NAME ,A.LAST_NAME, C.FIRST_NAME ,C.LAST_NAME) AS `Name`, CONCAT_WS(' ', ADDRESS_1, ADDRESS_2, ADDRESS_3, B.STATE_OR_PROVINCE, B.CITY, B.COUNTRY) AS 'Address', 'OFAC' AS 'List', 'INDIVIDUAL' AS 'Type'
	FROM OFAC AS A
	LEFT JOIN OFAC_ADDRESS AS B 
	ON A.DATAID = B.DATAID
	LEFT JOIN OFAC_ALIAS AS C
	ON A.DATAID = C.DATAID
	WHERE SDN_TYPE = 'Individual'
	AND A.DATE_INSERTED =(SELECT MAX(DATE_INSERTED)
				FROM OFAC)
				
	UNION

	SELECT DISTINCT (A.DATAID), CONCAT_WS(' ',A.FIRST_NAME ,A.LAST_NAME, C.FIRST_NAME ,C.LAST_NAME) AS `Name`, CONCAT_WS(' ', ADDRESS_1, ADDRESS_2, ADDRESS_3, B.STATE_OR_PROVINCE, B.CITY, B.COUNTRY) AS 'Address', 'OFAC' AS 'List', 'ENTITY' AS 'Type'
	FROM OFAC AS A
	LEFT JOIN OFAC_ADDRESS AS B 
	ON A.DATAID = B.DATAID
	LEFT JOIN OFAC_ALIAS AS C
	ON A.DATAID = C.DATAID	
	WHERE SDN_TYPE = 'Entity'
	AND A.DATE_INSERTED =(SELECT MAX(DATE_INSERTED)
				FROM OFAC)
				
				
	UNION
	
	SELECT DISTINCT (A.DATAID), CONCAT_WS(' ',A.FIRST_NAME ,A.LAST_NAME, C.FIRST_NAME ,C.LAST_NAME) AS `Name`, CONCAT_WS(' ', ADDRESS_1, ADDRESS_2, ADDRESS_3, B.STATE_OR_PROVINCE, B.CITY, B.COUNTRY) AS 'Address', 'OFAC_SDN' AS 'List', 'INDIVIDUAL' AS 'Type'
	FROM OFAC_SDN AS A
	LEFT JOIN OFAC_SDN_ADDRESS AS B 
	ON A.DATAID = B.DATAID
	LEFT JOIN OFAC_SDN_ALIAS AS C
	ON A.DATAID = C.DATAID
	WHERE SDN_TYPE = 'Individual'
	AND A.DATE_INSERTED =(SELECT MAX(DATE_INSERTED)
				FROM OFAC_SDN)
				
	UNION

	SELECT DISTINCT (A.DATAID), CONCAT_WS(' ',A.FIRST_NAME ,A.LAST_NAME, C.FIRST_NAME ,C.LAST_NAME) AS `Name`, CONCAT_WS(' ', ADDRESS_1, ADDRESS_2, ADDRESS_3, B.STATE_OR_PROVINCE, B.CITY, B.COUNTRY) AS 'Address', 'OFAC_SDN' AS 'List', 'ENTITY' AS 'Type'
	FROM OFAC_SDN AS A
	LEFT JOIN OFAC_SDN_ADDRESS AS B 
	ON A.DATAID = B.DATAID
	LEFT JOIN OFAC_SDN_ALIAS AS C
	ON A.DATAID = C.DATAID	
	WHERE SDN_TYPE = 'Entity'
	AND A.DATE_INSERTED =(SELECT MAX(DATE_INSERTED)
				FROM OFAC_SDN) 
	UNION

	SELECT DISTINCT(GROUPID) AS DATAID, CONCAT_WS(' ',FullName, name1, name2, name3, name4, name5, name6) AS `NAME`, CONCAT_WS(' ',address1, address2, address3, address4, address5, address6) AS 'Address', 'OFSI' AS 'List', 'INDIVIDUAL' AS 'Type'
	FROM OFSI
	WHERE FullName IS NOT NULL 
	AND GroupTypeDescription = 'INDIVIDUAL' 
	AND DATE_INSERTED =(SELECT MAX(DATE_INSERTED)
				FROM OFSI)			
				
	UNION

	SELECT DISTINCT(GROUPID) AS DATAID, CONCAT_WS(' ',FullName, name1, name2, name3, name4, name5, name6) AS `NAME`, CONCAT_WS(' ',address1, address2, address3, address4, address5, address6) AS 'Address', 'OFSI' AS 'List', 'ENTITY' AS 'Type'
	FROM OFSI
	WHERE FullName IS NOT NULL 
	AND GroupTypeDescription = 'Entity' 
	AND DATE_INSERTED =(SELECT MAX(DATE_INSERTED)
				FROM OFSI)
				
	UNION

	SELECT DISTINCT(Entity_LogicalId) AS DATAID, CONCAT_WS(' ',NameAlias_WholeName, NameAlias_FirstName, NameAlias_MiddleName, NameAlias_LastName) AS `Name`, CONCAT_WS(' ', Address_Street, Address_City, Address_CountryDescription) AS 'Address', 'EUFS' AS 'List' , 'INDIVIDUAL' AS 'Type'
	FROM EUFS
	WHERE (NameAlias_WholeName AND NameAlias_FirstName AND NameAlias_MiddleName AND NameAlias_LastName) IS NOT NULL 
	AND Entity_SubjectType_ClassificationCode = 'person'
	AND DATE_INSERTED =(SELECT MAX(DATE_INSERTED)
				FROM EUFS)
	UNION			
				
	SELECT DISTINCT(Entity_LogicalId) AS DATAID, CONCAT_WS(' ',NameAlias_WholeName, NameAlias_FirstName, NameAlias_MiddleName, NameAlias_LastName) AS `Name`, CONCAT_WS(' ', Address_Street, Address_City, Address_CountryDescription) AS 'Address', 'EUFS' AS 'List' , 'ENTITY' AS 'Type'
	FROM EUFS
	WHERE (NameAlias_WholeName AND NameAlias_FirstName AND NameAlias_MiddleName AND NameAlias_LastName) IS NOT NULL 
	AND Entity_SubjectType_ClassificationCode = 'enterprise'
	AND DATE_INSERTED =(SELECT MAX(DATE_INSERTED)
				FROM EUFS)
	

)AS A;
END //

CALL CONSOLIDATED_SEARCH_LIST()